theme: jekyll-theme-minimal

title: Rattana Pukdee
description: Email: rattanapukdee at gmail dot com , [[CV](https://drive.google.com/file/d/1azSlK8K_5BQJnTJpsl1KOqMY2cI3ND1p/view?usp=sharing)]
logo: logo.jpg
github:
  is_project_page: false
google_analytics: [G-9JQF1E3FMK]
